# testCallPyd.py
import python

def TestInclinationChange(pIAtkObjectRoot:ATKComponentPythonModule.IAtkObjectRoot):
    #新建场景
    pIAtkObject = pIAtkObjectRoot.GetChildren().New(python.eScenario, "InclinationChange")
    pIScenario = python.IAtkObject2IScenario(pIAtkObject)
    pIScenario.SetTimePeriod("5 Nov 2022 00:00:00.000", "8 Nov 2022 00:00:00.000")
    #新建卫星
    pIAtkObject = pIScenario.GetChildren().New(python.eSatellite, "SatInclinationChange")
    pISatellite = python.IAtkObject2ISatellite(pIAtkObject)
    pISatellite.SetPropagatorType(python.ePropagatorAstrogator)
    pIVADriverMCS = python.IVePropagator2IVADriverMCS(pISatellite.GetPropagator())
    pIVAMCSSegmentCollection = pIVADriverMCS.GetMainSequence()

    if (python.eVASegmentTypeInitialState != pIVAMCSSegmentCollection.Item(0).Type):
        return
    pIVAMCSInitialState = python.IVAMCSSegment2IVAMCSInitialState(pIVAMCSSegmentCollection.Item(0))
    pIVAMCSSegment00 = pIVAMCSSegmentCollection.Insert(python.eVASegmentTypePropagate, "Propagate", "-")
    pIVAMCSPropagate = python.IVAMCSSegment2IVAMCSPropagate(pIVAMCSSegment00)
    pIVAMCSSegment01 = pIVAMCSSegmentCollection.Insert(python.eVASegmentTypeTargetSequence, "TargetSequence", "-")
    pIVAMCSTargetSequence = python.IVAMCSSegment2IVAMCSTargetSequence(pIVAMCSSegment01)
    pIVAMCSSegmentCollection0 = pIVAMCSTargetSequence.GetSegments()
    pIVAMCSSegment02 = pIVAMCSSegmentCollection0.Insert(python.eVASegmentTypeManeuver, "Maneuver", "-")
    pIVAMCSManeuver = python.IVAMCSSegment2IVAMCSManeuver(pIVAMCSSegment02)
    pIVAMCSSegment10 = pIVAMCSSegmentCollection.Insert(python.eVASegmentTypePropagate, "Propagate1", "-")
    pIVAMCSPropagate1 = python.IVAMCSSegment2IVAMCSPropagate(pIVAMCSSegment10)
    pIVAMCSSegment11 = pIVAMCSSegmentCollection.Insert(python.eVASegmentTypeTargetSequence, "TargetSequence1", "-")
    pIVAMCSTargetSequence1 = python.IVAMCSSegment2IVAMCSTargetSequence(pIVAMCSSegment11)
    pIVAMCSSegmentCollection1 = pIVAMCSTargetSequence1.GetSegments()
    pIVAMCSSegment12 = pIVAMCSSegmentCollection1.Insert(python.eVASegmentTypeManeuver, "Maneuver", "-")
    pIVAMCSManeuver1 = python.IVAMCSSegment2IVAMCSManeuver(pIVAMCSSegment12)
    pIVAMCSSegment20 = pIVAMCSSegmentCollection.Insert(python.eVASegmentTypePropagate, "Propagate2", "-")
    pIVAMCSPropagate2 = python.IVAMCSSegment2IVAMCSPropagate(pIVAMCSSegment20)
    pIVAMCSSegment21 = pIVAMCSSegmentCollection.Insert(python.eVASegmentTypeTargetSequence, "TargetSequence2", "-")
    pIVAMCSTargetSequence2 = python.IVAMCSSegment2IVAMCSTargetSequence(pIVAMCSSegment21)
    pIVAMCSSegmentCollection2 = pIVAMCSTargetSequence2.GetSegments()
    pIVAMCSSegment22 = pIVAMCSSegmentCollection2.Insert(python.eVASegmentTypeManeuver, "Maneuver", "-")
    pIVAMCSManeuver2 = python.IVAMCSSegment2IVAMCSManeuver(pIVAMCSSegment22)
    pIVAMCSSegment30 = pIVAMCSSegmentCollection.Insert(python.eVASegmentTypePropagate, "Propagate3", "-")
    pIVAMCSPropagate3 = python.IVAMCSSegment2IVAMCSPropagate(pIVAMCSSegment30)
    pIVAMCSInitialState.SetOrbitEpoch("5 Nov 2022 00:00:00.000")
    pIVAMCSInitialState.SetElementType(python.eVAElementTypeKeplerian)
    pIVAElementKeplerian = python.IVAElement2IVAElementKeplerian(pIVAMCSInitialState.GetElement())
    pIVAElementKeplerian.SetSemiMajorAxis(6570)
    pIVAElementKeplerian.SetEccentricity(0)
    pIVAElementKeplerian.SetInclination(28)
    pIVAElementKeplerian.SetRAAN(0)
    pIVAElementKeplerian.SetArgOfPeriapsis(0)
    pIVAElementKeplerian.SetTrueAnomaly(0)
    pIVAStoppingConditionElement = pIVAMCSPropagate.GetStoppingConditions().Add("Duration")
    pIVAStoppingCondition = python.IVAStoppingConditionComponent2IVAStoppingCondition(pIVAStoppingConditionElement.GetProperties())
    pIVAStoppingCondition.SetTrip(7200)
    pIVAStoppingCondition.SetTolerance(0.0001)
    pIVAMCSManeuver.SetManeuverType(python.eVAManeuverTypeImpulsive)
    pIVAManeuverImpulsive = python.IVAManeuver2IVAManeuverImpulsive(pIVAMCSManeuver.GetManeuver())
    pIVAAttitudeControlImpulsiveThrustVector = python.IVAAttitudeControl2IVAAttitudeControlImpulsiveThrustVector(pIVAManeuverImpulsive.GetAttitudeControl())
    pIVAAttitudeControlImpulsiveThrustVector.SetThrustAxesName("Satellite VNC(Earth)")
    pIVAMCSManeuver.EnableControlParameter(python.eVAControlManeuverImpulsiveCartesianX)
    pIVAMCSManeuver.Results.Add("Radius_Of_Apoapsis")
    pIVAProfileDifferentialCorrector1 = python.IVAProfile2IVAProfileDifferentialCorrector1(pIVAMCSTargetSequence.GetProfiles().Add("Differential Corrector"))
    pIVADCControl = pIVAProfileDifferentialCorrector1.GetControlParameters().GetControlByPaths("Maneuver", "ImpulseX")
    pIVADCResult = pIVAProfileDifferentialCorrector1.GetResults().GetResultByPaths("Maneuver", "RadiusOfApoapsis")
    pIVADCControl = pIVAProfileDifferentialCorrector1.GetControlParameters().Item(0)
    pIVADCControl.SetEnable(True)
    pIVADCControl.SetMaxStep(100)
    #//pIVADCControl.SetCorrection(2456.42862556706)
    pIVADCControl.SetPerturbation(0.1)
    pIVADCControl.SetScalingValue(1)
    pIVADCResult = pIVAProfileDifferentialCorrector1.GetResults().Item(0)
    pIVADCResult.SetEnable(True)
    pIVADCResult.SetDesiredValue(42160000)
    pIVADCResult.SetScalingValue(1)
    pIVADCResult.SetTolerance(0.1)
    pIVADCResult.SetWeight(1)
    pIVAStoppingConditionElement1 = pIVAMCSPropagate1.GetStoppingConditions().Add("Apoapsis")
    pIVAStoppingCondition1 = python.IVAStoppingConditionComponent2IVAStoppingCondition(pIVAStoppingConditionElement1.GetProperties())
    pIVAStoppingCondition1.SetTolerance(0.0001)
    pIVAStoppingCondition1.SetRepeatCount(1)
    pIVAMCSManeuver1.SetManeuverType(python.eVAManeuverTypeImpulsive)
    pIVAManeuverImpulsive1 = python.IVAManeuver2IVAManeuverImpulsive(pIVAMCSManeuver1.GetManeuver())
    pIVAAttitudeControlImpulsiveThrustVector1 = python.IVAAttitudeControl2IVAAttitudeControlImpulsiveThrustVector(pIVAManeuverImpulsive1.GetAttitudeControl())
    pIVAAttitudeControlImpulsiveThrustVector1.SetThrustAxesName("Satellite VNC(Earth)")
    pIVAMCSManeuver1.EnableControlParameter(python.eVAControlManeuverImpulsiveCartesianX)
    pIVAMCSManeuver1.Results.Add("Eccentricity")
    pIVAProfileDifferentialCorrector11 = python.IVAProfile2IVAProfileDifferentialCorrector1(pIVAMCSTargetSequence1.GetProfiles().Add("Differential Corrector"))
    pIVADCControl1 = pIVAProfileDifferentialCorrector11.GetControlParameters().Item(0)
    pIVADCControl1.SetEnable(True)
    pIVADCControl1.SetMaxStep(100)
    pIVADCControl1.SetCorrection(1480.06329844802)
    pIVADCControl1.SetPerturbation(0.1)
    pIVADCControl1.SetScalingValue(1)
    pIVADCResult1 = pIVAProfileDifferentialCorrector11.GetResults().Item(0)
    pIVADCResult1.SetEnable(True)
    pIVADCResult1.SetDesiredValue(0)
    pIVADCResult1.SetScalingValue(1)
    pIVADCResult1.SetTolerance(0.001)
    pIVADCResult1.SetWeight(1)
    pIVAStoppingConditionElement2 = pIVAMCSPropagate2.GetStoppingConditions().Add("AscendingNode")
    pIVAStoppingCondition2 = python.IVAStoppingConditionComponent2IVAStoppingCondition(pIVAStoppingConditionElement2.GetProperties())
    pIVAStoppingCondition2.SetRepeatCount(2)
    pIVAStoppingCondition2.SetTolerance(1e-6)
    pIVAMCSManeuver2.SetManeuverType(python.eVAManeuverTypeImpulsive)
    pIVAManeuverImpulsive2 = python.IVAManeuver2IVAManeuverImpulsive(pIVAMCSManeuver2.GetManeuver())
    pIVAAttitudeControlImpulsiveThrustVector2 = python.IVAAttitudeControl2IVAAttitudeControlImpulsiveThrustVector(pIVAManeuverImpulsive2.GetAttitudeControl())
    pIVAAttitudeControlImpulsiveThrustVector2.SetThrustAxesName("Satellite VNC(Earth)")
    pIVAMCSManeuver2.EnableControlParameter(python.eVAControlManeuverImpulsiveCartesianX)
    pIVAMCSManeuver2.EnableControlParameter(python.eVAControlManeuverImpulsiveCartesianY)
    pIVAMCSManeuver2.Results.Add("Eccentricity")
    pIVAMCSManeuver2.Results.Add("Inclination")
    pIVAProfileDifferentialCorrector12 = python.IVAProfile2IVAProfileDifferentialCorrector1(pIVAMCSTargetSequence2.GetProfiles().Add("Differential Corrector"))
    pIVADCControl2 = pIVAProfileDifferentialCorrector12.GetControlParameters().Item(0)
    pIVADCControl2.SetEnable(True)
    pIVADCControl2.SetMaxStep(100)
    pIVADCControl2.SetCorrection(-359.983751789857)
    pIVADCControl2.SetPerturbation(0.1)
    pIVADCControl2.SetScalingValue(1)
    pIVADCControl3 = pIVAProfileDifferentialCorrector12.GetControlParameters().Item(1)
    pIVADCControl3.SetEnable(True)
    pIVADCControl3.SetMaxStep(100)
    pIVADCControl3.SetCorrection(-1444.72488992759)
    pIVADCControl3.SetPerturbation(0.1)
    pIVADCControl3.SetScalingValue(1)
    pIVADCResult2 = pIVAProfileDifferentialCorrector12.GetResults().Item(0)
    pIVADCResult2.SetEnable(True)
    pIVADCResult2.SetDesiredValue(0)
    pIVADCResult2.SetScalingValue(1)
    pIVADCResult2.SetTolerance(0)
    pIVADCResult2.SetWeight(1)
    pIVADCResult3 = pIVAProfileDifferentialCorrector12.GetResults().Item(1)
    pIVADCResult3.SetEnable(True)
    pIVADCResult3.SetDesiredValue(0)
    pIVADCResult3.SetScalingValue(1)
    pIVADCResult3.SetTolerance(0.001)
    pIVADCResult3.SetWeight(1)
    pIVAStoppingConditionElement3 = pIVAMCSPropagate3.GetStoppingConditions().Add("Duration")
    pIVAStoppingCondition3 = python.IVAStoppingConditionComponent2IVAStoppingCondition(pIVAStoppingConditionElement3.GetProperties())
    pIVAStoppingCondition3.SetTrip(129600)
    pIVAStoppingCondition3.SetTolerance(1e-5)
    pIVADriverMCS.RunMCS()
    pIVADriverMCS.ApplyAllProfileChanges()
    print(pIVAProfileDifferentialCorrector12)
#新建根节点
pIAtkObjectRoot = python.IAtkObjectRoot()
#倾角改变
TestInclinationChange(pIAtkObjectRoot)
#霍曼转移
#TestHohmannTransfer(pIAtkObjectRoot)
#仿真运行
pIAtkObjectRoot.m_Animation.PlayForward()
#输出数据报告
#pIAtkObjectRoot.OutputDataReport(pISate1, "地固系位置速度")
#保存场景
pIAtkObjectRoot.SaveScenario()
#关闭场景
pIAtkObjectRoot.CloseScenario()