import type { PathViewerText } from './types';

export const enPathViewerText: PathViewerText = {
  expand: 'Expand file list',
  collapse: 'Collapse file list',
  fileList: 'File List',
  configHint: 'After configuration, file paths are automatically joined into full paths. Click Copy to copy a path.',
  configBtn: 'Configure Root Path',
  rootPathLabel: 'ATK Root Path:',
  noRootTip: 'No software installation path configured. Relative paths are shown; configure one to get full absolute paths.',
  detectedPath: (p) => `🔍 Detected possible software path: ${p}`,
  quickConfig: 'Configure',
  emptyList: '📂 No files',
  copy: 'Copy',
  copyTitle: (p) => `Copy path: ${p}`,
  iconAlt: (ext) => `${ext} icon`,
  modalTitle: 'Configure Root Path',
  modalDesc: 'Enter the absolute path of the software installation directory; the file list will then be automatically joined into full paths.',
  placeholder: 'e.g. D:\\ProgramTool\\ATK-4.0-rc.4',
  autoFetchTitle: 'Auto-detect the software root path from the current page URL',
  autoFetch: 'Auto-detect',
  exampleHint: '<strong>Example:</strong> Suppose you enter the root path <code>D:\\ProgramTool\\ATK-4.0-rc.4</code> and the file list contains the path <code>Help\\Examples\\01-Getting Started</code>. The system automatically joins them into <code>D:\\ProgramTool\\ATK-4.0-rc.4\\Help\\Examples\\01-Getting Started</code>. Click the Copy button next to an item to copy its full path.',
  clearConfig: 'Clear',
  save: 'Save',
  cancel: 'Cancel',
  rootSet: (p) => `✅ Root path set: ${p}`,
  rootCleared: '🔄 Root path configuration cleared; showing original relative paths',
  detectedRoot: (p) => `🔍 Detected software root path: ${p}. Click "Configure Root Path" and save.`,
  notLocalEnv: '❌ Not in a local file environment; auto-detect is unavailable',
  autoFetched: (p) => `✅ Software path auto-detected: ${p}. Click "Save" to apply.`,
  autoFetchFail: '❌ Could not auto-detect the software root path; please enter it manually',
  copySuccess: (p) => `✅ Copied: ${p}`,
  copyFail: '❌ Copy failed; please copy manually',
  extractRootFail: 'Failed to extract root path:',
  saveConfigFail: 'Failed to save local configuration:',
  readConfigFail: 'Failed to read local configuration:',
  clipboardFail: 'Clipboard API copy failed:',
  invalidItem: 'Invalid path item:',
};
