import type { PathViewerText } from './types';

export const zhPathViewerText: PathViewerText = {
  expand: '展开文件列表',
  collapse: '折叠文件列表',
  fileList: '文件列表',
  configHint: '配置后文件列表将自动拼接为完整路径，点击“复制”按钮即可复制路径',
  configBtn: '配置软件根路径',
  rootPathLabel: 'ATK 根路径：',
  noRootTip: '当前未配置软件安装路径，展示的是相对路径，配置后可获取完整绝对路径',
  detectedPath: (p) => `🔍 检测到可能的软件路径：${p}`,
  quickConfig: '点击配置',
  emptyList: '📂 暂无文件列表',
  copy: '复制',
  copyTitle: (p) => `复制路径: ${p}`,
  iconAlt: (ext) => `${ext}图标`,
  modalTitle: '配置软件根路径',
  modalDesc: '请输入软件安装目录的绝对路径，之后文件列表会自动拼接为完整路径。',
  placeholder: '例如: D:\\ProgramTool\\ATK-4.0-rc.4',
  autoFetchTitle: '从当前页面URL自动提取软件根路径',
  autoFetch: '自动获取',
  exampleHint: '<strong>示例：</strong>假设您输入根路径 <code>D:\\ProgramTool\\ATK-4.0-rc.4</code>，文件列表中如有路径 <code>Help\\Examples\\01-入门案例</code>，系统会自动拼接为 <code>D:\\ProgramTool\\ATK-4.0-rc.4\\Help\\Examples\\01-入门案例</code>，点击对应项的“复制路径”按钮即可一键复制完整路径。',
  clearConfig: '清除配置',
  save: '保存',
  cancel: '取消',
  rootSet: (p) => `✅ 根路径已设置: ${p}`,
  rootCleared: '🔄 已清除根路径配置，现显示原始相对路径',
  detectedRoot: (p) => `🔍 检测到软件根路径: ${p}，请点击“配置软件根路径”并保存`,
  notLocalEnv: '❌ 当前不在本地文件环境，无法自动获取',
  autoFetched: (p) => `✅ 已自动获取软件路径: ${p}，请点击“保存”生效`,
  autoFetchFail: '❌ 未能自动识别软件根路径，请手动输入',
  copySuccess: (p) => `✅ 复制成功: ${p}`,
  copyFail: '❌ 复制失败，请手动复制',
  extractRootFail: '提取根路径失败:',
  saveConfigFail: '保存本地配置失败:',
  readConfigFail: '读取本地配置失败:',
  clipboardFail: 'Clipboard API 复制失败:',
  invalidItem: '无效的路径项:',
};
