name: Sync to GitHub Pages

on:
  push:
    branches:
      - master
      - develop

jobs:
  sync:
    runs-on: euleros-2.10.1
    steps:
      - uses: checkout-action@0.0.1
      
      - name: Configure git
        run: |
          git config user.name "GitCode CI"
          git config user.email "ci@gitcode.com"
      
      - name: Sync master to GitHub atk_doc
        if: github.ref_name == 'master'
        run: |
          echo "Syncing master to GitHub atk_doc..."
          git push https://xg_meow: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@github.com/xgMeow/atk_doc.git master:main -f
          echo "Sync master completed!"
      
      - name: Sync develop to GitHub atk_doc_dev
        if: github.ref_name == 'develop'
        run: |
          echo "Syncing develop to GitHub atk_doc_dev..."
          git push https://xg_meow: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@github.com/xgMeow/atk_doc_dev.git develop:main -f
          echo "Sync develop completed!"
